
# WebLogic Job Scheduler Data Store DDL for DB2
# Copyright (c) 2005 by BEA, Inc., All Rights Reserved

DROP TABLE WEBLOGIC_TIMERS;

CREATE TABLE WEBLOGIC_TIMERS (
  TIMER_ID VARCHAR(100) NOT NULL,
  LISTENER BLOB(32M) NOT NULL,
  START_TIME BIGINT NOT NULL,
  INTERVAL BIGINT NOT NULL,
  TIMER_MANAGER_NAME VARCHAR(100) NOT NULL,
  DOMAIN_NAME VARCHAR(100) NOT NULL,
  CLUSTER_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (TIMER_ID, CLUSTER_NAME, DOMAIN_NAME)
); 

