
# WebLogic Job Scheduler Data Store DDL for Informix
# Copyright (c) 2005 by BEA, Inc., All Rights Reserved

DROP TABLE WEBLOGIC_TIMERS;

CREATE TABLE WEBLOGIC_TIMERS (
  TIMER_ID VARCHAR(100) NOT NULL,
  LISTENER BYTE NOT NULL,
  START_TIME INT8 NOT NULL,
  INTERVAL INT8 NOT NULL,
  TIMER_MANAGER_NAME VARCHAR(100) NOT NULL,
  DOMAIN_NAME VARCHAR(100) NOT NULL,
  CLUSTER_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (TIMER_ID, CLUSTER_NAME, DOMAIN_NAME)
); 

